version: '3'
services:
  react-web:
    container_name: react-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - '/myapp/node_modules'
      - '.:/myapp'
